<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Currency;

class CurrencySeeder extends Seeder
{
    protected $currencyArray = [
        // Orden exacto según CountryTableSeeder.php (IDs 100-350)
        ['id' => 1, 'country_id' => 100, 'name' => 'Afghan Afghani', 'code' => 'AFN', 'precision' => 0, 'symbol' => 'Af', 'symbol_native' => '؋', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 2, 'country_id' => 101, 'name' => 'Albanian Lek', 'code' => 'ALL', 'precision' => 0, 'symbol' => 'ALL', 'symbol_native' => 'Lek', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 3, 'country_id' => 102, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 4, 'country_id' => 103, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 5, 'country_id' => 104, 'name' => 'Angolan Kwanza', 'code' => 'AOA', 'precision' => 2, 'symbol' => 'Kz', 'symbol_native' => 'Kz', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 6, 'country_id' => 105, 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 7, 'country_id' => 106, 'name' => 'Netherlands Antillean Guilder', 'code' => 'ANG', 'precision' => 2, 'symbol' => 'ƒ', 'symbol_native' => 'ƒ', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 8, 'country_id' => 107, 'name' => 'Saudi Riyal', 'code' => 'SAR', 'precision' => 2, 'symbol' => 'SR', 'symbol_native' => 'ر.س.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 9, 'country_id' => 108, 'name' => 'Algerian Dinar', 'code' => 'DZD', 'precision' => 2, 'symbol' => 'DA', 'symbol_native' => 'د.ج.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 10, 'country_id' => 109, 'name' => 'Argentine Peso', 'code' => 'ARS', 'precision' => 2, 'symbol' => 'AR$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 11, 'country_id' => 110, 'name' => 'Armenian Dram', 'code' => 'AMD', 'precision' => 0, 'symbol' => 'AMD', 'symbol_native' => 'դր.', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 12, 'country_id' => 111, 'name' => 'Aruban Florin', 'code' => 'AWG', 'precision' => 2, 'symbol' => 'ƒ', 'symbol_native' => 'ƒ', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 13, 'country_id' => 112, 'name' => 'Australian Dollar', 'code' => 'AUD', 'precision' => 2, 'symbol' => 'AU$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 14, 'country_id' => 113, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 15, 'country_id' => 114, 'name' => 'Azerbaijani Manat', 'code' => 'AZN', 'precision' => 2, 'symbol' => 'man.', 'symbol_native' => 'ман.', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 16, 'country_id' => 115, 'name' => 'Bahamian Dollar', 'code' => 'BSD', 'precision' => 2, 'symbol' => 'BS$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 17, 'country_id' => 116, 'name' => 'Bahraini Dinar', 'code' => 'BHD', 'precision' => 3, 'symbol' => 'BD', 'symbol_native' => 'د.ب.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 18, 'country_id' => 117, 'name' => 'Bangladeshi Taka', 'code' => 'BDT', 'precision' => 2, 'symbol' => 'Tk', 'symbol_native' => '৳', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 19, 'country_id' => 118, 'name' => 'Barbadian Dollar', 'code' => 'BBD', 'precision' => 2, 'symbol' => 'Bds$', 'symbol_native' => 'Bds$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 20, 'country_id' => 119, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 21, 'country_id' => 120, 'name' => 'Belize Dollar', 'code' => 'BZD', 'precision' => 2, 'symbol' => 'BZ$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 22, 'country_id' => 121, 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'precision' => 0, 'symbol' => 'CFA', 'symbol_native' => 'CFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 23, 'country_id' => 122, 'name' => 'Bermudian Dollar', 'code' => 'BMD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 24, 'country_id' => 123, 'name' => 'Bhutanese Ngultrum', 'code' => 'BTN', 'precision' => 2, 'symbol' => 'Nu.', 'symbol_native' => 'Nu.', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 25, 'country_id' => 124, 'name' => 'Belarusian Ruble', 'code' => 'BYN', 'precision' => 2, 'symbol' => 'Br', 'symbol_native' => 'руб.', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 26, 'country_id' => 125, 'name' => 'Bolivian Boliviano', 'code' => 'BOB', 'precision' => 2, 'symbol' => 'Bs', 'symbol_native' => 'Bs', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 27, 'country_id' => 126, 'name' => 'Bosnia-Herzegovina Convertible Mark', 'code' => 'BAM', 'precision' => 2, 'symbol' => 'KM', 'symbol_native' => 'KM', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 28, 'country_id' => 127, 'name' => 'Botswanan Pula', 'code' => 'BWP', 'precision' => 2, 'symbol' => 'BWP', 'symbol_native' => 'P', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 29, 'country_id' => 128, 'name' => 'Brazilian Real', 'code' => 'BRL', 'precision' => 2, 'symbol' => 'R$', 'symbol_native' => 'R$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 30, 'country_id' => 129, 'name' => 'Brunei Dollar', 'code' => 'BND', 'precision' => 2, 'symbol' => 'BN$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 31, 'country_id' => 130, 'name' => 'Bulgarian Lev', 'code' => 'BGN', 'precision' => 2, 'symbol' => 'BGN', 'symbol_native' => 'лв.', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 32, 'country_id' => 131, 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'precision' => 0, 'symbol' => 'CFA', 'symbol_native' => 'CFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 33, 'country_id' => 132, 'name' => 'Burundian Franc', 'code' => 'BIF', 'precision' => 0, 'symbol' => 'FBu', 'symbol_native' => 'FBu', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 34, 'country_id' => 133, 'name' => 'Cape Verdean Escudo', 'code' => 'CVE', 'precision' => 2, 'symbol' => 'CV$', 'symbol_native' => 'CV$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 35, 'country_id' => 134, 'name' => 'Cambodian Riel', 'code' => 'KHR', 'precision' => 2, 'symbol' => 'KHR', 'symbol_native' => '៛', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 36, 'country_id' => 135, 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'precision' => 0, 'symbol' => 'FCFA', 'symbol_native' => 'FCFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 37, 'country_id' => 136, 'name' => 'Canadian Dollar', 'code' => 'CAD', 'precision' => 2, 'symbol' => 'CA$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 38, 'country_id' => 137, 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'precision' => 0, 'symbol' => 'FCFA', 'symbol_native' => 'FCFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 39, 'country_id' => 138, 'name' => 'Chilean Peso', 'code' => 'CLP', 'precision' => 0, 'symbol' => 'CL$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 40, 'country_id' => 139, 'name' => 'Chinese Yuan', 'code' => 'CNY', 'precision' => 2, 'symbol' => 'CN¥', 'symbol_native' => 'CN¥', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 41, 'country_id' => 140, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 42, 'country_id' => 141, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 43, 'country_id' => 142, 'name' => 'Colombian Peso', 'code' => 'COP', 'precision' => 0, 'symbol' => 'CO$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 44, 'country_id' => 143, 'name' => 'Comoran Franc', 'code' => 'KMF', 'precision' => 0, 'symbol' => 'CF', 'symbol_native' => 'FC', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 45, 'country_id' => 144, 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'precision' => 0, 'symbol' => 'FCFA', 'symbol_native' => 'FCFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 46, 'country_id' => 145, 'name' => 'North Korean Won', 'code' => 'KPW', 'precision' => 0, 'symbol' => '₩', 'symbol_native' => '₩', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 47, 'country_id' => 146, 'name' => 'South Korean Won', 'code' => 'KRW', 'precision' => 0, 'symbol' => '₩', 'symbol_native' => '₩', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 48, 'country_id' => 147, 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'precision' => 0, 'symbol' => 'CFA', 'symbol_native' => 'CFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 49, 'country_id' => 148, 'name' => 'Costa Rican Colon', 'code' => 'CRC', 'precision' => 0, 'symbol' => '₡', 'symbol_native' => '₡', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 50, 'country_id' => 149, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 51, 'country_id' => 150, 'name' => 'Cuban Convertible Peso', 'code' => 'CUC', 'precision' => 2, 'symbol' => 'CUC$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 52, 'country_id' => 151, 'name' => 'Danish Krone', 'code' => 'DKK', 'precision' => 2, 'symbol' => 'kr', 'symbol_native' => 'kr', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 53, 'country_id' => 153, 'name' => 'Dominican Peso', 'code' => 'DOP', 'precision' => 2, 'symbol' => 'RD$', 'symbol_native' => 'RD$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 54, 'country_id' => 154, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 55, 'country_id' => 155, 'name' => 'Egyptian Pound', 'code' => 'EGP', 'precision' => 2, 'symbol' => 'E£', 'symbol_native' => 'ج.م.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 56, 'country_id' => 156, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 57, 'country_id' => 157, 'name' => 'UAE Dirham', 'code' => 'AED', 'precision' => 2, 'symbol' => 'AED', 'symbol_native' => 'د.إ.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 58, 'country_id' => 158, 'name' => 'Eritrean Nakfa', 'code' => 'ERN', 'precision' => 2, 'symbol' => 'Nfk', 'symbol_native' => 'Nfk', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 59, 'country_id' => 159, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 60, 'country_id' => 160, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 61, 'country_id' => 161, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 62, 'country_id' => 162, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 63, 'country_id' => 163, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 64, 'country_id' => 164, 'name' => 'Ethiopian Birr', 'code' => 'ETB', 'precision' => 2, 'symbol' => 'Br', 'symbol_native' => 'Br', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 65, 'country_id' => 165, 'name' => 'Russian Ruble', 'code' => 'RUB', 'precision' => 2, 'symbol' => '₽', 'symbol_native' => '₽', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 66, 'country_id' => 166, 'name' => 'Fijian Dollar', 'code' => 'FJD', 'precision' => 2, 'symbol' => 'FJ$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 67, 'country_id' => 167, 'name' => 'Philippine Peso', 'code' => 'PHP', 'precision' => 2, 'symbol' => '₱', 'symbol_native' => '₱', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 68, 'country_id' => 168, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 69, 'country_id' => 169, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 70, 'country_id' => 170, 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'precision' => 0, 'symbol' => 'FCFA', 'symbol_native' => 'FCFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 71, 'country_id' => 171, 'name' => 'Gambian Dalasi', 'code' => 'GMD', 'precision' => 2, 'symbol' => 'D', 'symbol_native' => 'D', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 72, 'country_id' => 172, 'name' => 'Georgian Lari', 'code' => 'GEL', 'precision' => 2, 'symbol' => 'GEL', 'symbol_native' => 'ლ', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 73, 'country_id' => 173, 'name' => 'Ghanaian Cedi', 'code' => 'GHS', 'precision' => 2, 'symbol' => 'GH₵', 'symbol_native' => 'GH₵', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 74, 'country_id' => 174, 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'precision' => 2, 'symbol' => 'EC$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 75, 'country_id' => 175, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 76, 'country_id' => 176, 'name' => 'Guatemalan Quetzal', 'code' => 'GTQ', 'precision' => 2, 'symbol' => 'Q', 'symbol_native' => 'Q', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 77, 'country_id' => 177, 'name' => 'Guyanaese Dollar', 'code' => 'GYD', 'precision' => 2, 'symbol' => 'GY$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 78, 'country_id' => 178, 'name' => 'Guinean Franc', 'code' => 'GNF', 'precision' => 0, 'symbol' => 'FG', 'symbol_native' => 'FG', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 79, 'country_id' => 179, 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'precision' => 0, 'symbol' => 'CFA', 'symbol_native' => 'CFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 80, 'country_id' => 180, 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'precision' => 0, 'symbol' => 'FCFA', 'symbol_native' => 'FCFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 81, 'country_id' => 181, 'name' => 'Haitian Gourde', 'code' => 'HTG', 'precision' => 2, 'symbol' => 'HTG', 'symbol_native' => 'HTG', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 82, 'country_id' => 182, 'name' => 'Honduran Lempira', 'code' => 'HNL', 'precision' => 2, 'symbol' => 'L', 'symbol_native' => 'L', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 83, 'country_id' => 183, 'name' => 'Hong Kong Dollar', 'code' => 'HKD', 'precision' => 2, 'symbol' => 'HK$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 84, 'country_id' => 184, 'name' => 'Hungarian Forint', 'code' => 'HUF', 'precision' => 0, 'symbol' => 'Ft', 'symbol_native' => 'Ft', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 85, 'country_id' => 185, 'name' => 'Indian Rupee', 'code' => 'INR', 'precision' => 2, 'symbol' => '₹', 'symbol_native' => '₹', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 86, 'country_id' => 186, 'name' => 'Indonesian Rupiah', 'code' => 'IDR', 'precision' => 2, 'symbol' => 'Rp', 'symbol_native' => 'Rp', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 87, 'country_id' => 187, 'name' => 'Iraqi Dinar', 'code' => 'IQD', 'precision' => 3, 'symbol' => 'IQD', 'symbol_native' => 'د.ع.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 88, 'country_id' => 188, 'name' => 'Iranian Rial', 'code' => 'IRR', 'precision' => 2, 'symbol' => 'IRR', 'symbol_native' => '﷼', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 89, 'country_id' => 189, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 90, 'country_id' => 190, 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'precision' => 2, 'symbol' => 'NZ$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 91, 'country_id' => 191, 'name' => 'Icelandic Krona', 'code' => 'ISK', 'precision' => 0, 'symbol' => 'kr', 'symbol_native' => 'kr', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 92, 'country_id' => 192, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 93, 'country_id' => 193, 'name' => 'Solomon Islands Dollar', 'code' => 'SBD', 'precision' => 2, 'symbol' => 'SI$', 'symbol_native' => 'SI$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 94, 'country_id' => 194, 'name' => 'Seychellois Rupee', 'code' => 'SCR', 'precision' => 2, 'symbol' => 'SRe', 'symbol_native' => 'SRe', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 95, 'country_id' => 195, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 96, 'country_id' => 196, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 97, 'country_id' => 197, 'name' => 'Israeli New Sheqel', 'code' => 'ILS', 'precision' => 2, 'symbol' => '₪', 'symbol_native' => '₪', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 98, 'country_id' => 198, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 99, 'country_id' => 199, 'name' => 'Libyan Dinar', 'code' => 'LYD', 'precision' => 3, 'symbol' => 'LD', 'symbol_native' => 'د.ل.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 100, 'country_id' => 200, 'name' => 'Jamaican Dollar', 'code' => 'JMD', 'precision' => 2, 'symbol' => 'J$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 101, 'country_id' => 201, 'name' => 'Japanese Yen', 'code' => 'JPY', 'precision' => 0, 'symbol' => '¥', 'symbol_native' => '￥', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 102, 'country_id' => 202, 'name' => 'Jordanian Dinar', 'code' => 'JOD', 'precision' => 3, 'symbol' => 'JD', 'symbol_native' => 'د.أ.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 103, 'country_id' => 203, 'name' => 'Kazakhstani Tenge', 'code' => 'KZT', 'precision' => 2, 'symbol' => '₸', 'symbol_native' => 'тңг.', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 104, 'country_id' => 204, 'name' => 'Kenyan Shilling', 'code' => 'KES', 'precision' => 2, 'symbol' => 'Ksh', 'symbol_native' => 'Ksh', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 105, 'country_id' => 205, 'name' => 'Kyrgystani Som', 'code' => 'KGS', 'precision' => 2, 'symbol' => 'KGS', 'symbol_native' => 'сом', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 106, 'country_id' => 206, 'name' => 'Australian Dollar', 'code' => 'AUD', 'precision' => 2, 'symbol' => 'AU$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 107, 'country_id' => 207, 'name' => 'Kuwaiti Dinar', 'code' => 'KWD', 'precision' => 3, 'symbol' => 'KD', 'symbol_native' => 'د.ك.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 108, 'country_id' => 208, 'name' => 'Macedonian Denar', 'code' => 'MKD', 'precision' => 2, 'symbol' => 'ден', 'symbol_native' => 'ден', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 109, 'country_id' => 209, 'name' => 'Swiss Franc', 'code' => 'CHF', 'precision' => 2, 'symbol' => 'CHF', 'symbol_native' => 'CHF', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 110, 'country_id' => 210, 'name' => 'Lesotho Loti', 'code' => 'LSL', 'precision' => 2, 'symbol' => 'L', 'symbol_native' => 'L', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 111, 'country_id' => 211, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 112, 'country_id' => 212, 'name' => 'Lebanese Pound', 'code' => 'LBP', 'precision' => 2, 'symbol' => 'LB£', 'symbol_native' => 'ل.ل.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 113, 'country_id' => 213, 'name' => 'Liberian Dollar', 'code' => 'LRD', 'precision' => 2, 'symbol' => 'L$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 114, 'country_id' => 214, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 115, 'country_id' => 215, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 116, 'country_id' => 216, 'name' => 'Macanese Pataca', 'code' => 'MOP', 'precision' => 2, 'symbol' => 'MOP$', 'symbol_native' => 'MOP$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 117, 'country_id' => 217, 'name' => 'Malagasy Ariary', 'code' => 'MGA', 'precision' => 0, 'symbol' => 'Ar', 'symbol_native' => 'Ar', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 118, 'country_id' => 218, 'name' => 'Malaysian Ringgit', 'code' => 'MYR', 'precision' => 2, 'symbol' => 'RM', 'symbol_native' => 'RM', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 119, 'country_id' => 219, 'name' => 'Malawian Kwacha', 'code' => 'MWK', 'precision' => 2, 'symbol' => 'MK', 'symbol_native' => 'MK', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 120, 'country_id' => 220, 'name' => 'Maldivian Rufiyaa', 'code' => 'MVR', 'precision' => 2, 'symbol' => 'Rf', 'symbol_native' => 'ރ.', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 121, 'country_id' => 221, 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'precision' => 0, 'symbol' => 'CFA', 'symbol_native' => 'CFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 122, 'country_id' => 222, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 123, 'country_id' => 223, 'name' => 'Moroccan Dirham', 'code' => 'MAD', 'precision' => 2, 'symbol' => 'MAD', 'symbol_native' => 'د.م.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 124, 'country_id' => 224, 'name' => 'Mauritian Rupee', 'code' => 'MUR', 'precision' => 2, 'symbol' => 'Rs', 'symbol_native' => 'Rs', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 125, 'country_id' => 225, 'name' => 'Mauritanian Ouguiya', 'code' => 'MRU', 'precision' => 2, 'symbol' => 'UM', 'symbol_native' => 'أ.م', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 126, 'country_id' => 226, 'name' => 'Mexican Peso', 'code' => 'MXN', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 127, 'country_id' => 227, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 128, 'country_id' => 228, 'name' => 'Moldovan Leu', 'code' => 'MDL', 'precision' => 2, 'symbol' => 'L', 'symbol_native' => 'L', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 129, 'country_id' => 229, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 130, 'country_id' => 230, 'name' => 'Mongolian Tugrik', 'code' => 'MNT', 'precision' => 2, 'symbol' => '₮', 'symbol_native' => '₮', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 131, 'country_id' => 231, 'name' => 'Mozambican Metical', 'code' => 'MZN', 'precision' => 2, 'symbol' => 'MT', 'symbol_native' => 'MT', 'symbol_first' => 1, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 132, 'country_id' => 232, 'name' => 'Myanmar Kyat', 'code' => 'MMK', 'precision' => 2, 'symbol' => 'K', 'symbol_native' => 'K', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 133, 'country_id' => 233, 'name' => 'Namibian Dollar', 'code' => 'NAD', 'precision' => 2, 'symbol' => 'N$', 'symbol_native' => 'N$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 134, 'country_id' => 234, 'name' => 'Australian Dollar', 'code' => 'AUD', 'precision' => 2, 'symbol' => 'AU$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 135, 'country_id' => 235, 'name' => 'Nepalese Rupee', 'code' => 'NPR', 'precision' => 2, 'symbol' => 'Rs', 'symbol_native' => 'नेरू', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 136, 'country_id' => 236, 'name' => 'Nicaraguan Córdoba', 'code' => 'NIO', 'precision' => 2, 'symbol' => 'C$', 'symbol_native' => 'C$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 137, 'country_id' => 237, 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'precision' => 0, 'symbol' => 'CFA', 'symbol_native' => 'CFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 138, 'country_id' => 238, 'name' => 'Nigerian Naira', 'code' => 'NGN', 'precision' => 2, 'symbol' => '₦', 'symbol_native' => '₦', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 139, 'country_id' => 239, 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'precision' => 2, 'symbol' => 'NZ$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 140, 'country_id' => 240, 'name' => 'Norwegian Krone', 'code' => 'NOK', 'precision' => 2, 'symbol' => 'kr', 'symbol_native' => 'kr', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 141, 'country_id' => 241, 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'precision' => 2, 'symbol' => 'NZ$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 142, 'country_id' => 242, 'name' => 'Omani Rial', 'code' => 'OMR', 'precision' => 3, 'symbol' => 'ر.ع.', 'symbol_native' => 'ر.ع.', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 143, 'country_id' => 243, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 144, 'country_id' => 244, 'name' => 'Pakistani Rupee', 'code' => 'PKR', 'precision' => 2, 'symbol' => 'Rs', 'symbol_native' => '₨', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 145, 'country_id' => 245, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 146, 'country_id' => 246, 'name' => 'Israeli New Sheqel', 'code' => 'ILS', 'precision' => 2, 'symbol' => '₪', 'symbol_native' => '₪', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 147, 'country_id' => 247, 'name' => 'Panamanian Balboa', 'code' => 'PAB', 'precision' => 2, 'symbol' => 'B/.', 'symbol_native' => 'B/.', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 148, 'country_id' => 248, 'name' => 'Papua New Guinean Kina', 'code' => 'PGK', 'precision' => 2, 'symbol' => 'K', 'symbol_native' => 'K', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 149, 'country_id' => 249, 'name' => 'Paraguayan Guarani', 'code' => 'PYG', 'precision' => 0, 'symbol' => '₲', 'symbol_native' => '₲', 'symbol_first' => 1, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 150, 'country_id' => 250, 'name' => 'Peruvian Sol', 'code' => 'PEN', 'precision' => 2, 'symbol' => 'S/', 'symbol_native' => 'S/', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 151, 'country_id' => 251, 'name' => 'Polish Zloty', 'code' => 'PLN', 'precision' => 2, 'symbol' => 'zł', 'symbol_native' => 'zł', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 152, 'country_id' => 252, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 153, 'country_id' => 253, 'name' => 'Qatari Rial', 'code' => 'QAR', 'precision' => 2, 'symbol' => 'QR', 'symbol_native' => 'ر.ق.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 154, 'country_id' => 254, 'name' => 'British Pound Sterling', 'code' => 'GBP', 'precision' => 2, 'symbol' => '£', 'symbol_native' => '£', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 155, 'country_id' => 255, 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'precision' => 0, 'symbol' => 'FCFA', 'symbol_native' => 'FCFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 156, 'country_id' => 256, 'name' => 'Czech Republic Koruna', 'code' => 'CZK', 'precision' => 2, 'symbol' => 'Kč', 'symbol_native' => 'Kč', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 157, 'country_id' => 257, 'name' => 'Congolese Franc', 'code' => 'CDF', 'precision' => 2, 'symbol' => 'FC', 'symbol_native' => 'FC', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 158, 'country_id' => 258, 'name' => 'Dominican Peso', 'code' => 'DOP', 'precision' => 2, 'symbol' => 'RD$', 'symbol_native' => 'RD$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 159, 'country_id' => 259, 'name' => 'Lao Kip', 'code' => 'LAK', 'precision' => 2, 'symbol' => '₭', 'symbol_native' => '₭', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 160, 'country_id' => 260, 'name' => 'Tanzanian Shilling', 'code' => 'TZS', 'precision' => 2, 'symbol' => 'TSh', 'symbol_native' => 'TSh', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 161, 'country_id' => 261, 'name' => 'Romanian Leu', 'code' => 'RON', 'precision' => 2, 'symbol' => 'lei', 'symbol_native' => 'lei', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 162, 'country_id' => 262, 'name' => 'Rwandan Franc', 'code' => 'RWF', 'precision' => 0, 'symbol' => 'RWF', 'symbol_native' => 'FR', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 163, 'country_id' => 263, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 164, 'country_id' => 264, 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'precision' => 2, 'symbol' => 'EC$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 165, 'country_id' => 265, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 166, 'country_id' => 266, 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'precision' => 2, 'symbol' => 'EC$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 167, 'country_id' => 267, 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'precision' => 2, 'symbol' => 'EC$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 168, 'country_id' => 268, 'name' => 'São Tomé and Príncipe Dobra', 'code' => 'STN', 'precision' => 2, 'symbol' => 'Db', 'symbol_native' => 'Db', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 169, 'country_id' => 269, 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'precision' => 0, 'symbol' => 'CFA', 'symbol_native' => 'CFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 170, 'country_id' => 270, 'name' => 'Sierra Leonean Leone', 'code' => 'SLL', 'precision' => 2, 'symbol' => 'Le', 'symbol_native' => 'Le', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 171, 'country_id' => 271, 'name' => 'Singapore Dollar', 'code' => 'SGD', 'precision' => 2, 'symbol' => 'S$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 172, 'country_id' => 272, 'name' => 'Syrian Pound', 'code' => 'SYP', 'precision' => 2, 'symbol' => 'SY£', 'symbol_native' => 'ل.س.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 173, 'country_id' => 273, 'name' => 'Somali Shilling', 'code' => 'SOS', 'precision' => 2, 'symbol' => 'Sh', 'symbol_native' => 'Sh', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 174, 'country_id' => 274, 'name' => 'Sri Lankan Rupee', 'code' => 'LKR', 'precision' => 2, 'symbol' => 'Rs', 'symbol_native' => 'SL Re', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 175, 'country_id' => 275, 'name' => 'South African Rand', 'code' => 'ZAR', 'precision' => 2, 'symbol' => 'R', 'symbol_native' => 'R', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 176, 'country_id' => 276, 'name' => 'Sudanese Pound', 'code' => 'SDG', 'precision' => 2, 'symbol' => 'SDG', 'symbol_native' => 'SDG', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 177, 'country_id' => 277, 'name' => 'Swedish Krona', 'code' => 'SEK', 'precision' => 2, 'symbol' => 'kr', 'symbol_native' => 'kr', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 178, 'country_id' => 278, 'name' => 'Swiss Franc', 'code' => 'CHF', 'precision' => 2, 'symbol' => 'CHF', 'symbol_native' => 'CHF', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 179, 'country_id' => 279, 'name' => 'Surinamese Dollar', 'code' => 'SRD', 'precision' => 2, 'symbol' => 'Sr$', 'symbol_native' => 'Sr$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 180, 'country_id' => 280, 'name' => 'Swazi Lilangeni', 'code' => 'SZL', 'precision' => 2, 'symbol' => 'E', 'symbol_native' => 'E', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 181, 'country_id' => 281, 'name' => 'Thai Baht', 'code' => 'THB', 'precision' => 2, 'symbol' => '฿', 'symbol_native' => '฿', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 182, 'country_id' => 282, 'name' => 'Australian Dollar', 'code' => 'AUD', 'precision' => 2, 'symbol' => 'AU$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 183, 'country_id' => 283, 'name' => 'Tajikistani Somoni', 'code' => 'TJS', 'precision' => 2, 'symbol' => 'SM', 'symbol_native' => 'SM', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 184, 'country_id' => 284, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 185, 'country_id' => 285, 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'precision' => 0, 'symbol' => 'CFA', 'symbol_native' => 'CFA', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 186, 'country_id' => 286, 'name' => 'Tongan Paʻanga', 'code' => 'TOP', 'precision' => 2, 'symbol' => 'T$', 'symbol_native' => 'T$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 187, 'country_id' => 287, 'name' => 'Trinidad and Tobago Dollar', 'code' => 'TTD', 'precision' => 2, 'symbol' => 'TT$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 188, 'country_id' => 288, 'name' => 'Tunisian Dinar', 'code' => 'TND', 'precision' => 3, 'symbol' => 'DT', 'symbol_native' => 'د.ت.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 189, 'country_id' => 289, 'name' => 'Turkmenistani Manat', 'code' => 'TMT', 'precision' => 2, 'symbol' => 'T', 'symbol_native' => 'T', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 190, 'country_id' => 290, 'name' => 'Turkish Lira', 'code' => 'TRY', 'precision' => 2, 'symbol' => '₺', 'symbol_native' => '₺', 'symbol_first' => 1, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 191, 'country_id' => 291, 'name' => 'Ukrainian Hryvnia', 'code' => 'UAH', 'precision' => 2, 'symbol' => '₴', 'symbol_native' => '₴', 'symbol_first' => 1, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 192, 'country_id' => 292, 'name' => 'Ugandan Shilling', 'code' => 'UGX', 'precision' => 0, 'symbol' => 'USh', 'symbol_native' => 'USh', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 193, 'country_id' => 293, 'name' => 'Uruguayan Peso', 'code' => 'UYU', 'precision' => 2, 'symbol' => '$U', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 194, 'country_id' => 294, 'name' => 'Uzbekistan Som', 'code' => 'UZS', 'precision' => 2, 'symbol' => 'so\'m', 'symbol_native' => 'so\'m', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 195, 'country_id' => 295, 'name' => 'Vanuatu Vatu', 'code' => 'VUV', 'precision' => 0, 'symbol' => 'VT', 'symbol_native' => 'VT', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 196, 'country_id' => 296, 'name' => 'Venezuelan Bolívar', 'code' => 'VES', 'precision' => 2, 'symbol' => 'Bs.S', 'symbol_native' => 'Bs.S', 'symbol_first' => 1, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 197, 'country_id' => 297, 'name' => 'Vietnamese Dong', 'code' => 'VND', 'precision' => 0, 'symbol' => '₫', 'symbol_native' => '₫', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 198, 'country_id' => 298, 'name' => 'Yemeni Rial', 'code' => 'YER', 'precision' => 2, 'symbol' => 'YR', 'symbol_native' => 'ر.ي.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 199, 'country_id' => 300, 'name' => 'Zambian Kwacha', 'code' => 'ZMW', 'precision' => 2, 'symbol' => 'ZK', 'symbol_native' => 'ZK', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 200, 'country_id' => 301, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 201, 'country_id' => 303, 'name' => 'British Pound Sterling', 'code' => 'GBP', 'precision' => 2, 'symbol' => '£', 'symbol_native' => '£', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 202, 'country_id' => 304, 'name' => 'New Taiwan Dollar', 'code' => 'TWD', 'precision' => 2, 'symbol' => 'NT$', 'symbol_native' => 'NT$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 203, 'country_id' => 305, 'name' => 'New Taiwan Dollar', 'code' => 'TWD', 'precision' => 2, 'symbol' => 'NT$', 'symbol_native' => 'NT$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 204, 'country_id' => 306, 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'precision' => 2, 'symbol' => 'EC$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 205, 'country_id' => 308, 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'precision' => 2, 'symbol' => 'EC$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 206, 'country_id' => 310, 'name' => 'Gibraltar Pound', 'code' => 'GIP', 'precision' => 2, 'symbol' => '£', 'symbol_native' => '£', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 207, 'country_id' => 311, 'name' => 'Danish Krone', 'code' => 'DKK', 'precision' => 2, 'symbol' => 'kr', 'symbol_native' => 'kr', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 208, 'country_id' => 313, 'name' => 'Cayman Islands Dollar', 'code' => 'KYD', 'precision' => 2, 'symbol' => 'CI$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 209, 'country_id' => 314, 'name' => 'Australian Dollar', 'code' => 'AUD', 'precision' => 2, 'symbol' => 'AU$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 210, 'country_id' => 315, 'name' => 'Faroese Króna', 'code' => 'DKK', 'precision' => 2, 'symbol' => 'kr', 'symbol_native' => 'kr', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 211, 'country_id' => 316, 'name' => 'Falkland Islands Pound', 'code' => 'FKP', 'precision' => 2, 'symbol' => '£', 'symbol_native' => '£', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 212, 'country_id' => 317, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 213, 'country_id' => 318, 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'precision' => 2, 'symbol' => 'NZ$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 214, 'country_id' => 319, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 215, 'country_id' => 320, 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'precision' => 2, 'symbol' => 'EC$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 216, 'country_id' => 322, 'name' => 'CFP Franc', 'code' => 'XPF', 'precision' => 0, 'symbol' => '₣', 'symbol_native' => '₣', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 217, 'country_id' => 323, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 218, 'country_id' => 324, 'name' => 'Moroccan Dirham', 'code' => 'MAD', 'precision' => 2, 'symbol' => 'MAD', 'symbol_native' => 'د.م.‏', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 219, 'country_id' => 325, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 220, 'country_id' => 326, 'name' => 'Norwegian Krone', 'code' => 'NOK', 'precision' => 2, 'symbol' => 'kr', 'symbol_native' => 'kr', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 221, 'country_id' => 327, 'name' => 'Tanzanian Shilling', 'code' => 'TZS', 'precision' => 2, 'symbol' => 'TSh', 'symbol_native' => 'TSh', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 222, 'country_id' => 328, 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'precision' => 2, 'symbol' => 'NZ$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 223, 'country_id' => 329, 'name' => 'CFP Franc', 'code' => 'XPF', 'precision' => 0, 'symbol' => '₣', 'symbol_native' => '₣', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 224, 'country_id' => 331, 'name' => 'Djiboutian Franc', 'code' => 'DJF', 'precision' => 0, 'symbol' => 'Fdj', 'symbol_native' => 'Fdj', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 225, 'country_id' => 332, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 226, 'country_id' => 333, 'name' => 'Norwegian Krone', 'code' => 'NOK', 'precision' => 2, 'symbol' => 'kr', 'symbol_native' => 'kr', 'symbol_first' => 0, 'decimal_mark' => ',', 'thousands_separator' => '.'],
        ['id' => 227, 'country_id' => 334, 'name' => 'Saint Helena Pound', 'code' => 'SHP', 'precision' => 2, 'symbol' => '£', 'symbol_native' => '£', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 228, 'country_id' => 335, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 229, 'country_id' => 336, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 230, 'country_id' => 337, 'name' => 'No official currency', 'code' => 'XXX', 'precision' => 0, 'symbol' => '', 'symbol_native' => '', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 231, 'country_id' => 338, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 232, 'country_id' => 339, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 233, 'country_id' => 340, 'name' => 'CFP Franc', 'code' => 'XPF', 'precision' => 0, 'symbol' => '₣', 'symbol_native' => '₣', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 234, 'country_id' => 341, 'name' => 'Australian Dollar', 'code' => 'AUD', 'precision' => 2, 'symbol' => 'AU$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 235, 'country_id' => 342, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 236, 'country_id' => 343, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 237, 'country_id' => 344, 'name' => 'Australian Dollar', 'code' => 'AUD', 'precision' => 2, 'symbol' => 'AU$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 238, 'country_id' => 345, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 239, 'country_id' => 346, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 240, 'country_id' => 347, 'name' => 'British Pound Sterling', 'code' => 'GBP', 'precision' => 2, 'symbol' => '£', 'symbol_native' => '£', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 241, 'country_id' => 348, 'name' => 'US Dollar', 'code' => 'USD', 'precision' => 2, 'symbol' => '$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 242, 'country_id' => 349, 'name' => 'Euro', 'code' => 'EUR', 'precision' => 2, 'symbol' => '€', 'symbol_native' => '€', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        ['id' => 243, 'country_id' => 350, 'name' => 'Australian Dollar', 'code' => 'AUD', 'precision' => 2, 'symbol' => 'AU$', 'symbol_native' => '$', 'symbol_first' => 1, 'decimal_mark' => '.', 'thousands_separator' => ','],
        
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->currencyArray as $value) {
            Currency::create($value);
        }

        $this->adjustAutoIncrement('currencies');
    }

    protected function adjustAutoIncrement(string $table)
    {
        $maxId = DB::table($table)->max('id') + 1;

        $driver = DB::getDriverName();

        if ($driver === 'pgsql') {
            $sequenceName = $table . '_id_seq';
            DB::statement("SELECT setval('$sequenceName', $maxId)");
        } elseif ($driver === 'mysql' || $driver === 'mariadb') {
            DB::statement("ALTER TABLE $table AUTO_INCREMENT = $maxId");
        } elseif ($driver === 'sqlite') {
            DB::statement("UPDATE sqlite_sequence SET seq = $maxId WHERE name = '$table'");
        } else {
            throw new \Exception('Unsupported database driver: ' . $driver);
        }
    }
} 