import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
        './vendor/livewire/livewire/dist/**/*.blade.php',
    ],
    theme: {
        screens: {
            xs: '400px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1536px',
        },
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                'dv-display': ['Metropolis', 'ui-serif', ...defaultTheme.fontFamily.serif],
                'dv-body': ['Inter', ...defaultTheme.fontFamily.sans],
                'dv-label': ['Geist Sans', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'dv-display-lg': ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.02em', fontWeight: '700' }],
                'dv-headline-lg': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.01em', fontWeight: '600' }],
                'dv-headline-lg-mobile': ['1.75rem', { lineHeight: '2.25rem', fontWeight: '600' }],
                'dv-headline-md': ['1.5rem', { lineHeight: '2rem', fontWeight: '600' }],
                'dv-body-lg': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '400' }],
                'dv-body-md': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
                'dv-body-sm': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
                'dv-label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.05em', fontWeight: '500' }],
            },
            spacing: {
                'margin-desktop': '2.5rem',
                'margin-mobile': '1rem',
                gutter: '1.5rem',
                'stack-sm': '0.5rem',
                'stack-md': '1rem',
                'stack-lg': '2rem',
            },
            maxWidth: {
                dv: '1280px',
            },
            colors: {
                // ── Sistema existente (admin panel) ──
                primary: {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                },
                success: {
                    50: '#f0fdf4',
                    100: '#dcfce7',
                    200: '#bbf7d0',
                    300: '#86efac',
                    400: '#4ade80',
                    500: '#22c55e',
                    600: '#16a34a',
                    700: '#15803d',
                    800: '#166534',
                    900: '#14532d',
                },
                warning: {
                    50: '#fffbeb',
                    100: '#fef3c7',
                    200: '#fde68a',
                    300: '#fcd34d',
                    400: '#fbbf24',
                    500: '#f59e0b',
                    600: '#d97706',
                    700: '#b45309',
                    800: '#92400e',
                    900: '#78350f',
                },
                danger: {
                    50: '#fef2f2',
                    100: '#fee2e2',
                    200: '#fecaca',
                    300: '#fca5a5',
                    400: '#f87171',
                    500: '#ef4444',
                    600: '#dc2626',
                    700: '#b91c1c',
                    800: '#991b1b',
                    900: '#7f1d1d',
                },

                // ── Digital Vault · Catálogo público ──
                'dv-surface': '#15121b',
                'dv-surface-dim': '#15121b',
                'dv-surface-bright': '#3b3742',
                'dv-surface-container-lowest': '#0f0d15',
                'dv-surface-container-low': '#1d1a23',
                'dv-surface-container': '#211e27',
                'dv-surface-container-high': '#2c2832',
                'dv-surface-container-highest': '#37333d',
                'dv-on-surface': '#e7e0ed',
                'dv-on-surface-variant': '#cbc3d7',
                'dv-outline': '#958ea0',
                'dv-outline-variant': '#494454',
                'dv-primary': '#d0bcff',
                'dv-on-primary': '#3c0091',
                'dv-primary-container': '#a078ff',
                'dv-on-primary-container': '#340080',
                'dv-secondary': '#4cd7f6',
                'dv-on-secondary': '#003640',
                'dv-secondary-container': '#03b5d3',
                'dv-on-secondary-container': '#00424e',
                'dv-tertiary': '#ffb869',
                'dv-on-tertiary': '#482900',
                'dv-tertiary-container': '#ca801e',
                'dv-on-tertiary-container': '#3f2300',
                'dv-background': '#15121b',
                'dv-on-background': '#e7e0ed',
                'dv-inverse-surface': '#e7e0ed',
                'dv-inverse-on-surface': '#322f39',
                'dv-inverse-primary': '#6d3bd7',
                'dv-surface-tint': '#d0bcff',
                'dv-surface-variant': '#37333d',
                'dv-error-container': '#93000a',
                'dv-on-error-container': '#ffdad6',
                'dv-primary-fixed': '#e9ddff',
                'dv-primary-fixed-dim': '#d0bcff',
                'dv-on-primary-fixed': '#23005c',
                'dv-on-primary-fixed-variant': '#5516be',
                'dv-secondary-fixed': '#acedff',
                'dv-secondary-fixed-dim': '#4cd7f6',
                'dv-on-secondary-fixed': '#001f26',
                'dv-on-secondary-fixed-variant': '#004e5c',
                'dv-on-tertiary-fixed-variant': '#673d00',
                'dv-error': '#ffb4ab',
                'dv-on-error': '#690005',
            },
            animation: {
                'fade-in': 'fadeIn 0.3s ease-in-out',
                'slide-in': 'slideIn 0.3s ease-out',
                'bounce-in': 'bounceIn 0.6s ease-out',
                'catalog-fade-up': 'catalogFadeUp 0.48s ease-out both',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0', transform: 'translateY(-10px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                slideIn: {
                    '0%': { transform: 'translateX(-100%)' },
                    '100%': { transform: 'translateX(0)' },
                },
                bounceIn: {
                    '0%': { opacity: '0', transform: 'scale(0.3)' },
                    '50%': { opacity: '1', transform: 'scale(1.05)' },
                    '70%': { transform: 'scale(0.9)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                catalogFadeUp: {
                    from: { opacity: '0', transform: 'translateY(20px)' },
                    to: { opacity: '1', transform: 'translateY(0)' },
                },
            },
            boxShadow: {
                'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
                'medium': '0 4px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
    ],
};
